### ISSUE TITLE
Unable to make Cubes subtraction

### ISSUE THREAD

**Issue by Seremonik** [hecomi/uRaymarching#17]
Unity 2018.3.2f1
Im unable to make subtraction of two cubes.
visual glitches appear:

![image](https://user-images.githubusercontent.com/9090982/52650790-330a0e00-2eeb-11e9-8257-aca80085a2a7.png)

distance function:
inline float DistanceFunction(float3 pos)
{
float x = Box(pos,float3(1,1,1));
pos-= float3(0.5,0.5,0.5);
float y = Box(pos,float3(1,1,1));
//float v = Sphere(pos, 1); (uncoment and change -x to -v below to see it working with sphere)
return max(y,-x);
}

**Comment by hecomi** [comment]
Thanks for reporting. I've just started trying to fix it.

**Comment by hecomi** [comment]
Fixed! Please try the latest .unitypackage from the release page (https://github.com/hecomi/uRaymarching/releases/tag/v1.0.2).

In my environment, it worked.
```hlsl
inline float DistanceFunction(float3 pos)
{
  float x = Box(pos, 1);
  pos -= float3(0.5, 0.5, 0.5);
  float y = Box(pos, 1);
  return max(-y, x);
}
```
<img width="706" alt="bug-fix" src="https://user-images.githubusercontent.com/493433/52895823-f39d3380-3202-11e9-9fbd-62b9dfa6c87d.PNG">

w/ self shadow
<img width="527" alt="with-shadow" src="https://user-images.githubusercontent.com/493433/52895832-1a5b6a00-3203-11e9-9d3c-8fe77d3fe977.PNG">

**Comment by Seremonik** [comment]
Works! But right now im unable to zoom into object because its dissapearing,
And when im changing material to "Follow Object Size"
this happens with your code above:
![image](https://user-images.githubusercontent.com/9090982/52897487-68597900-31d5-11e9-9a54-4d819df01f84.png)

Can you confirm if you can see this cubes subtraction from inside?

**Comment by hecomi** [comment]
1. Zoom into object
Please check `Camera Inside Object` in the `Conditions` section and set `Culling` as `Off` in the `Material Properties` section. `Camera Inside Object` generates a code to check whether the start position of a ray is inside the object or not.

2. Follow Object Size
Ummm, it seems to be an another bug. I'll start trying to fix it soon, but if possible could you create a new issue for this problem?

**Comment by Seremonik** [comment]
1. You are right, thank you :)
2. of course, here you go 
https://github.com/hecomi/uRaymarching/issues/18

**Comment by hecomi** [comment]
Thanks a lot!
