### ISSUE TITLE
Different rendering per object

### ISSUE THREAD

**Issue by PxSonny** [hecomi/uRaymarching#2]
Hi, 

I am doing the union of two primitives in my distance function. But how can I have a different rendering between both? In my scene I'd like one to be textured and the others keep a unique color. 

Thanks.

**Comment by hecomi** [comment]
There seems to be some techniques to change texture or color of each distance function. I think the easiest method with uRaymarching is re-checking the distances of each function also in `PostEffect`.

**DistanceFunction**
```c
inline float SphereA(float3 pos)
{
    return Sphere(pos - float3(-0.5, 0.0, 0.0), 0.5);
}

inline float SphereB(float3 pos)
{
    return Sphere(pos - float3(0.5, 0.0, 0.0), 0.5);
}

inline float DistanceFunction(float3 pos)
{
    return min(SphereA(pos), SphereB(pos));
}
```

**PostEffect**
```c
inline void PostEffect(RaymarchInfo ray, inout PostEffectOutput o)
{
    float3 pos = ToLocal(ray.endPos); // do not forget convert the position to local one.
    float epsilon = ray.minDistance;
    if      (SphereA(pos) <= epsilon) o.Albedo = float4(1, 0, 0, 1);
    else if (SphereB(pos) <= epsilon) o.Albedo = float4(0, 0, 1, 1);
}
```

![ball](https://cloud.githubusercontent.com/assets/493433/21606876/ca3a493e-d1f5-11e6-993f-c9feeb312840.PNG)

**Comment by PxSonny** [comment]
Thank you it works nicely.
