### ISSUE TITLE
Rendering Mandelbulb black screen

### ISSUE THREAD

**Issue by daBlesr** [hecomi/uRaymarching#20]
Dear Hecomi,

I'm trying to render a MandelBulb, one described with a distance formula on [http://blog.hvidtfeldts.net/index.php/2011/09/distance-estimated-3d-fractals-v-the-mandelbulb-different-de-approximations/](http://blog.hvidtfeldts.net/index.php/2011/09/distance-estimated-3d-fractals-v-the-mandelbulb-different-de-approximations/). However, the screen is entirely black. Could you please give me some heads up on what I am doing wrong? I have also included the test project in a zip file. I have tried to stay as close to the working "Mod World" example from this repo for testing purposes.
![Capture](https://user-images.githubusercontent.com/8330830/58766154-9774da00-857b-11e9-8334-1a966cf5f89e.PNG)
![Capture2](https://user-images.githubusercontent.com/8330830/58766155-9774da00-857b-11e9-998f-da9d393810e6.PNG)
![Capture3](https://user-images.githubusercontent.com/8330830/58766156-9774da00-857b-11e9-822b-959473192772.PNG)

[mandelbulb-test-project.zip](https://github.com/hecomi/uRaymarching/files/3245116/mandelbulb-test-project.zip)

Best regards,

daBlesr

**Comment by hecomi** [comment]
Sorry for my late reply...
You added the iteration count as `_Iteration` but you are using it as `_Iterations` (***s*** shouldn't be added to the variable). I could see the MandelBulb like this (tweaked some parameters to make it interesting):
![image](https://user-images.githubusercontent.com/493433/71782737-c7f48900-3020-11ea-9848-387fa7e9bce1.png)
