### ISSUE TITLE
Rendering breaks when using forward rather than deferred

### ISSUE THREAD

**Issue by andybak** [hecomi/uRaymarching#7]
I'm keen to use uRaymarching in VR but I've hit a couple of snags. I'll write up this one first as it's simple to describe.

I need to use the forward renderer to enable MSAA (which I guess won't benefit the raymarched objects but will benefit the rest of the scene). 

However when I switch to forward - the placeholder geometry is rendered as well as the raymarched "geometry".

**Comment by kaldrax7** [comment]
Unfortunately, deferred rendering is required in order for raymarching to work.

**Comment by andybak** [comment]
You make it sound like *all* raymarching requires deferred rendering. I've got a fair few raymarching experiments working with forward rendering. What specifically in your project requires deferred rendering? Is it something related to the z-buffer integration?

**Comment by hecomi** [comment]
Sorry for my late reply...

I have a plan to support forward rendering in the future. The reason why I'm using deferred rendering is  that the implementation is much simpler and easier than forward rendering.

**Comment by hecomi** [comment]
Now we can use forward from v1.0.0.
