### ISSUE TITLE
Metal Support

### ISSUE THREAD

**Issue by JohnnyErnest** [hecomi/uRaymarching#9]
Really neat project. It doesn't work on Unity 2017.2/OSX when switching over to Metal API (which I want for a particular project that uses Compute Shaders on Metal as it's faster than OpenGL on my project), just switches over to a blank texture. Wondering what it would take to get that working.

**Comment by hecomi** [comment]
Sorry for my late reply...
I've fixed Metal-related problems in this release: https://github.com/hecomi/uRaymarching/releases/tag/v0.0.3
